### ISSUE TITLE
setup.sh fails

### ISSUE THREAD

**Issue by jhalterman** [abailly/jepsen-vagrant#2]
setup.sh currently fails during vagrant up and when run manually. The failure seems to be around the JDK install.

**Comment by justizin** [comment]
Can you paste the output?

Also, try the workaround (detailed in the README), which I noted in response to #3, of manually running the scripts after logging in with 'vagrant ssh'.

**Comment by jhalterman** [comment]
The output from the initial `vagrant up` is mangled so I can't tell exactly how far the setup makes it. But if I ssh to the box and manually run setupsh, the output ends with:

```
You might want to run 'apt-get -f install' to correct these:
The following packages have unmet dependencies:
 libc-bin : Depends: libc6 (< 2.19) but 2.19-18 is to be installed
 libc-dev-bin : Depends: libc6 (< 2.19) but 2.19-18 is to be installed
 libc6-dev : Depends: libc6 (= 2.18-5) but 2.19-18 is to be installed
 locales : Depends: libc-bin (> 2.19) but 2.18-5 is to be installed
 oracle-java8-installer : Depends: java-common (>= 0.24) but it is not going to be installed
                          Recommends: gsfonts-x11 but it is not going to be installed
E: Unmet dependencies. Try 'apt-get -f install' with no packages (or specify a solution).
```

Running `apt-get -f install` does repair things, after which `bash setup.sh` appears to work.

**Comment by jhalterman** [comment]
This seems to have been caused (for whatever reason) by running an older vagrant. Closing!
